# Generated by Django 3.2.4 on 2021-07-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210716_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addition',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
