# Generated by Django 3.2.4 on 2021-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210710_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
