# Generated by Django 3.2.4 on 2021-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
    ]
