# Generated by Django 3.2.4 on 2021-08-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
